root: true
extends:
  - eslint-config-mlauffer-nodejs
  - plugin:jsdoc/recommended-typescript
  - plugin:@typescript-eslint/recommended
  #- plugin:wdio/recommended
env:
  mocha: true
  qunit: true
parser: "@typescript-eslint/parser"
rules:
  jsdoc/require-param: off
  jsdoc/require-returns: off
