name: test

on:
  push:
  pull_request:

permissions: read-all

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22, 24]
    permissions:
      checks: write
    steps:
      - uses: actions/checkout@v7
      - uses: pnpm/action-setup@v6
        with:
          cache: true
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}
          cache: pnpm
      - run: pnpm ci
      - run: pnpm run build
      - run: pnpm run test:wdio
      - run: pnpm run test:qunit
      - run: pnpm run test:ui5:unit
      - run: pnpm run test:ui5:opa
      # - run: pnpm run test:no:specs
      - name: Test Report
        uses: dorny/test-reporter@v3
        if: always()
        with:
          name: WDIO QUnit Service
          path: test-results/results-*.xml
          reporter: jest-junit
      - run: pnpm run lint
